name: products_view
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.3.2
  sizer: ^2.0.15
  lottie: ^2.6.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/lottile/
    - asset/images/

  